SELECT

  stg_international_players.all_player_count_rolling_48
, stg_international_players.all_player_points_rolling_48

, stg_international_tournaments.all_tournament_count
, stg_international_tournaments.all_wppr_points

, stg_player_stats_all.all_player_wpprtunist
, stg_player_stats_all.all_player_traveler
, stg_player_stats_all.all_player_localsupporter
, stg_player_stats_all.all_player_onetimer
, stg_player_stats_all.all_player_nonactive
, stg_player_stats_all.all_perc_player_wpprtunist
, stg_player_stats_all.all_perc_player_traveler
, stg_player_stats_all.all_perc_player_localsupporter
, stg_player_stats_all.all_perc_player_onetimer
, stg_player_stats_all.all_perc_player_nonactive

, stg_geography_stats_tournaments_all.all_tournament_wpprtunist
, stg_geography_stats_tournaments_all.all_tournament_traveler
, stg_geography_stats_tournaments_all.all_tournament_localsupporter
, stg_geography_stats_tournaments_all.all_tournament_onetimer
, stg_geography_stats_tournaments_all.all_tournament_mixedpersona
, stg_geography_stats_tournaments_all.all_tournament_nonactive
, stg_geography_stats_tournaments_all.all_tournaments

, stg_geography_stats_tournaments_all.all_perc_tournament_wpprtunist
, stg_geography_stats_tournaments_all.all_perc_tournament_traveler
, stg_geography_stats_tournaments_all.all_perc_tournament_localsupporter
, stg_geography_stats_tournaments_all.all_perc_tournament_onetimer
, stg_geography_stats_tournaments_all.all_perc_tournament_mixedpersona
, stg_geography_stats_tournaments_all.all_perc_tournament_nonactive

, stg_geography_player_bins_all.all_player_bin_010
, stg_geography_player_bins_all.all_player_bin_020
, stg_geography_player_bins_all.all_player_bin_030
, stg_geography_player_bins_all.all_player_bin_040
, stg_geography_player_bins_all.all_player_bin_050
, stg_geography_player_bins_all.all_player_bin_060
, stg_geography_player_bins_all.all_player_bin_070
, stg_geography_player_bins_all.all_player_bin_080
, stg_geography_player_bins_all.all_player_bin_090
, stg_geography_player_bins_all.all_player_bin_100
, stg_geography_player_bins_all.all_player_bin_100_plus

, stg_geography_player_bins_all.all_player_bin_010_perc
, stg_geography_player_bins_all.all_player_bin_020_perc
, stg_geography_player_bins_all.all_player_bin_030_perc
, stg_geography_player_bins_all.all_player_bin_040_perc
, stg_geography_player_bins_all.all_player_bin_050_perc
, stg_geography_player_bins_all.all_player_bin_060_perc
, stg_geography_player_bins_all.all_player_bin_070_perc
, stg_geography_player_bins_all.all_player_bin_080_perc
, stg_geography_player_bins_all.all_player_bin_090_perc
, stg_geography_player_bins_all.all_player_bin_100_perc
, stg_geography_player_bins_all.all_player_bin_100_plus_perc

FROM {{ ref('stg_international_players') }} stg_international_players
LEFT JOIN {{ ref('stg_international_tournaments') }} stg_international_tournaments
ON 1=1
LEFT JOIN {{ ref('stg_player_stats_all') }} stg_player_stats_all
ON 1=1
LEFT JOIN {{ ref('stg_geography_stats_tournaments_all') }} stg_geography_stats_tournaments_all
ON 1=1
LEFT JOIN {{ ref('stg_geography_player_bins_all') }} stg_geography_player_bins_all
ON 1=1
